### ISSUE TITLE
Build problem with Vite

### ISSUE THREAD

**Issue by jordcodes** [twickstrom/vue-papa-parse#4]
**Describe the bug**
In a Typescript Vue 3 Vite project and I get an error importing the package. I see the following error:

 [ERROR] Cannot assign to import "download"

    node_modules/vue-papa-parse/src/index.js:46:9:
      46 │     Papa.download = _downloadCsv
         ╵          ~~~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "setDownload") and then import and call that function here
  instead.

✘ [ERROR] Cannot assign to import "dedupe"

    node_modules/vue-papa-parse/src/index.js:47:9:
      47 │     Papa.dedupe = _dedupe
         ╵          ~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "setDedupe") and then import and call that function here
  instead.

Does the package support Vite?

**Comment by twickstrom** [comment]
Quick fix. I’ll push a fix later today. Thanks for the heads up!

**Comment by jordcodes** [comment]
Awesome thanks @twickstrom really appreciate it. 

I also see the same error on with download. 

 [ERROR] Cannot assign to import "download"

    node_modules/vue-papa-parse/src/index.js:46:9:
      46 │     Papa.download = _downloadCsv
         ╵          ~~~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "setDownload") and then import and call that function here
  instead.

**Comment by twickstrom** [comment]
> Imports are immutable in JavaScript.

Installed latest vite and I am not getting this error. Can you please provide steps to reproduce?

**Comment by jarrodw-cs** [comment]
Hi @twickstrom, I've run into this issue too. Replication steps:

1. Create a new Vue 3 + Vite project
```bash
yarn create vite
```
```bash
✔ Project name: … vite-project
✔ Select a framework: › vue
✔ Select a variant: › vue-ts

Scaffolding project in vite-project...

Done. Now run:

  cd vite-project
  yarn
  yarn dev

✨  Done in 15.63s.
```

2. Add `vue-papa-parse` as a dependency and register it as a plugin
```bash
yarn add vue-papa-parse
```
`main.ts`
```typescript
import { createApp } from 'vue'
import App from './App.vue'

import VuePapaParse from 'vue-papa-parse'

const app = createApp(App)

app.use(VuePapaParse)
app.mount('#app')

```

3. Run the Vite dev server, receive an error
```bash
yarn dev
```
output:
```bash
yarn run v1.22.15
$ vite

  vite v2.8.4 dev server running at:

  > Local: http://localhost:XXXX/
  > Network: use `--host` to expose

  ready in 315ms.

XX:XX:XX [vite] new dependencies found: vue-papa-parse, updating...
✘ [ERROR] Cannot assign to import "download"

    node_modules/vue-papa-parse/src/index.js:46:9:
      46 │     Papa.download = _downloadCsv
         ╵          ~~~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "setDownload") and then import and call that function here
  instead.

✘ [ERROR] Cannot assign to import "dedupe"

    node_modules/vue-papa-parse/src/index.js:47:9:
      47 │     Papa.dedupe = _dedupe
         ╵          ~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "setDedupe") and then import and call that function here
  instead.

XX:XX:XX [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/vue-papa-parse/src/index.js:46:9: ERROR: Cannot assign to import "download"
node_modules/vue-papa-parse/src/index.js:47:9: ERROR: Cannot assign to import "dedupe"
```

**Comment by tpoisot** [comment]
Same issue here with npm v. 8.5.3

~~~
papaparse: ^5.3.1,
vue: ^3.2.31,
vue-papa-parse: ^3.0.4,
vuetable-2: ^2.0.0-beta.4
~~~

**Comment by rachitpant** [comment]
I can also confirm this issue exists.
If i update the plugin to use a local variable instead of trying to update the import directly , its working fine.
```
const VuePapaParse = {
  install (app, options) {
    let localPapa = Papa
    localPapa.download = _downloadCsv
    localPapa.dedupe = _dedupe
    if ('config' in app && 'globalProperties' in app.config) {
      app.config.globalProperties.$papa = localPapa
    } else {
      app.prototype.$papa = localPapa
    }
  }
}

export default VuePapaParse
```

Please let me know if you want me to send a PR.

**Comment by talbenyamin** [comment]
1
